docs: add Azure Firewall scrape
promitor/docs pull request #64
Opened 2024-09-18 17:05 UTC by locmai

Update for https://github.com/tomkerkhove/promitor/pull/2545

2024-09-20 14:20 UTC, tomkerkhove requested changes

2024-09-20 14:20 UTC, tomkerkhove commented on docs/scraping/providers/azure-firewall.md
> +# Azure Automation account
Can you align please?

2024-09-20 14:20 UTC, tomkerkhove commented on docs/scraping/providers/azure-firewall.md
> +![Availability Badge](https://img.shields.io/badge/Available%20Starting-v2.1-green.svg)![Resource Discovery Support Badge](https://img.shields.io/badge/Support%20for%20Resource%20Discovery-Yes-green.
```suggestion
![Availability Badge](https://img.shields.io/badge/Available%20Starting-v2.12-green.svg)![Resource Discovery Support Badge](https://img.shields.io/badge/Support%20for%20Resource%20Discovery-Yes-green.svg)
```

2024-09-20 14:20 UTC, tomkerkhove commented on docs/scraping/providers/azure-firewall.md
> +You can scrape an Azure Automation account via the `AzureFirewall`
```suggestion
You can scrape an Azure Firewall via the `AzureFirewall`
```

2024-09-20 14:20 UTC, tomkerkhove commented on docs/scraping/providers/azure-firewall.md
> +## Example
Nit
```suggestion
## Example
```

2024-09-20 14:20 UTC, tomkerkhove commented on docs/scraping/providers/azure-firewall.md
> +
Nit
```suggestion

```

2024-10-28 02:54 UTC, locmai commented on docs/scraping/providers/azure-firewall.md
> +# Azure Automation account
Hi, fixed!

2024-10-28 09:46 UTC, tomkerkhove approved these changes

2024-10-28 09:46 UTC, merged