feat: Adding SDKDefault Authentication
promitor/docs pull request #67
Opened 2024-11-25 09:38 UTC by jayendranarumugam

As part of https://github.com/tomkerkhove/promitor/pull/2578 updating the docs

-Enabling DefaultAzureAuth

2024-11-25 09:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/promitor/docs?pullRequest=67) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/promitor/docs?pullRequest=67) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/promitor/docs?pullRequest=67) it.</sub>

2024-11-25 10:04 UTC, tomkerkhove requested changes

2024-11-25 10:04 UTC, tomkerkhove commented on docs/resource-discovery/runtime-configuration.md
> +  # Options are ServicePrincipal, SystemAssignedManagedIdentity, UserAssignedManagedIdentity, SdkDefault.
Can you please update section above?

2024-11-25 10:04 UTC, tomkerkhove commented on docs/security/azure-authentication.md
> +  # Options are ServicePrincipal, SystemAssignedManagedIdentity, UserAssignedManagedIdentity, SdkDefault.
Same here, update Supported Authentication Mechanisms

2024-11-27 05:51 UTC, jayendranarumugam commented on docs/resource-discovery/runtime-configuration.md
> +  # Options are ServicePrincipal, SystemAssignedManagedIdentity, UserAssignedManagedIdentity, SdkDefault.
Updated please check now

2024-11-27 05:51 UTC, jayendranarumugam commented on docs/security/azure-authentication.md
> +  # Options are ServicePrincipal, SystemAssignedManagedIdentity, UserAssignedManagedIdentity, SdkDefault.
Updated

2024-11-27 06:37 UTC, tomkerkhove commented
Thank you!

2024-11-27 06:38 UTC, merged